services:
  - type: web
    name: alex-io-site
    runtime: node
    repo: https://github.com/Beancheeze1/Alex-io-site
    branch: main
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      # OAuth (fill with your real values in the Render dashboard or here)
      - key: HUBSPOT_CLIENT_ID
        sync: false
      - key: HUBSPOT_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_PORTAL_ID
        sync: false
      - key: HUBSPOT_PRIVATE_APP_TOKEN
        sync: false
      - key: HUBSPOT_SCOPES
        value: "oauth files crm.objects.deals.read crm.objects.contacts.read"
      # Public/base URLs
      - key: APP_BASE_URL
        value: https://alex-io-site.onrender.com
      - key: HUBSPOT_REDIRECT_URI
        value: https://alex-io-site.onrender.com/api/auth/hubspot/callback
      # Upstash/Redis etc. (if you use them)
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
